
events {
    worker_connections 1024;
}


http {
    server {
        listen 80;

        server_name hello.127.0.0.1.nip.io;

        location / {
            proxy_pass http://nodeserver:3000;
        }
    }

    server {
        listen 80;

        server_name time.127.0.0.1.nip.io;

        location / {
            proxy_pass http://nodetime:3000;
        }
    }

    server {
        listen 80;

        server_name users.127.0.0.1.nip.io;

        location / {
            proxy_pass http://nodeuser:3000;
        }
    }
}